name: build test benchmark 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - run: mkdir build && cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF && cmake --build build
      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            build/bin/tests

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: |
          chmod +x tests
          GTEST_BREAK_ON_FAILURE=1 CURL_VERBOSE=1 ./tests 2>&1 | tee test.log
